# Generated by Django 4.2.2 on 2025-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a name", max_length=200, unique=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter a last name", max_length=200, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter an email", max_length=254, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="persona",
            constraint=models.UniqueConstraint(
                fields=("id",),
                name="unique_person_id",
                violation_error_message="Id already exists",
            ),
        ),
    ]
