# Generated by Django 4.2.2 on 2025-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_persona_unique_person_id_alter_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='last_name',
            field=models.CharField(help_text='Enter a last name', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(help_text='Enter a name', max_length=200),
        ),
    ]
