# Generated by Django 4.2.2 on 2025-03-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_persona_last_name_alter_persona_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='nombre',
        ),
    ]
