# Generated by Django 4.2.2 on 2025-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_last_name_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(help_text='Enter a last name', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(help_text='Enter a name', max_length=200),
        ),
    ]
